name: Dashboard
name: Dashboard-ci
on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Lint code
        run: |
          flake8 app tests
      - name: Code formatting
        run: |
          black . --check
      - name: Type checking
        run: |
          mypy app tests
      - name: Sort imports
        run: |
          isort app tests
      - name: Run tests
        run: |
          pytest tests
